language: java
jdk:
    - oraclejdk8
    - oraclejdk7
branches:
#   except:
    only:
        - master
notifications:
    email:
        recipients:
#           -
        on_success: always #always、never與change
        on_failure: always #always、never與change

beforeinstall:

install:

beforescript:

script:
    - javac . MySorter.java
    - javac . -cp junit-4.12.jar MySorterMain.java MySorterTest.java
    - java MySorterMain
    - java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore MySorterTest

after_success:

after_failure:

before_deploy:

deploy:

after_deploy:

after_script: